export const FETCH_INVENTORY_DATA_REQUEST = "FETCH_INVENTORY_DATA_REQUEST";
export const FETCH_INVENTORY_DATA_SUCCESS = "FETCH_INVENTORY_DATA_SUCCESS";
export const FETCH_INVENTORY_DATA_FAILURE = "FETCH_INVENTORY_DATA_FAILURE";
